# Setup
title: Lab127
tagline: The Jekyll Butler
description: Web Development. IT Services.
url: ""
baseurl: ""

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: rouge
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/page:num/"

# Compressed sass.
sass:
  style: compressed

# Contact
contact:
  phone: 6285640241433
  email: demmidel@gmail.com

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:title/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      is_post: true # set is_post=true {{ page.is_post }}
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: post
      comments: true
      share: true


# Custom vars
version: 1.0.0
github:
  repo: //github.com/lab127/lab127.github.io

# Site Author
author:
  name: Lab127
  avatar: lab127-150x.jpg
  bio: ""

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
